# Generated by Django 3.2.8 on 2021-12-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskB_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='defo', upload_to='taskB/')),
                ('pred_price', models.FloatField()),
            ],
        ),
    ]
