version: '3'
services:
  python3:
    restart: always
    ports:
      - "8888:8888"
      - "8000:8000"
    build: .
    container_name: NFT_API 
    working_dir: '/root/'
    tty: true
    volumes:
      - .:/root/
      - ./src:/root/src:ro
